FROM swr.cn-south-1.myhuaweicloud.com/ascendhub/cann:9.1.0-950-ubuntu22.04-py3.12
RUN sed -i 's@http://archive.ubuntu.com/ubuntu/@https://repo.huaweicloud.com/ubuntu/@g' /etc/apt/sources.list && \
    sed -i 's@http://security.ubuntu.com/ubuntu/@https://repo.huaweicloud.com/ubuntu/@g' /etc/apt/sources.list && \
     apt-get update && \
     apt-get install -y libgl1 libglib2.0-0 libgomp1 && \
     apt-get install -y \
        python3.10 \
        python3.10-dev \
        python3.10-venv \
        python3-pip && \
     /usr/bin/python3.10 -m venv /opt/py310
ENV PATH="/opt/py310/bin:$PATH" FEATURE_BACKEND=ascend
COPY . /app
WORKDIR /app
RUN pip config set global.index-url https://repo.huaweicloud.com/repository/pypi/simple && \
    pip install --no-cache-dir /app/ascend_patchs/common/*.whl && \
    pip install --no-cache-dir -r requirements.ascend950pr.amd 
CMD ["python", "-m", "feature.main"]
